base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (UserRegister,
                    Logout,
                    VerifyOtp,
                    Dashboard,
                    ResetPasswordView,
                    ForgotPasswordView,
                    ResendOtp, ChangePassword
                    )

from base.api import UserLoginView

app_name = "base"

urlpatterns = [
    # path("register/", UserRegister.as_view(), name="register"),
    path("dashboard/", login_required(Dashboard.as_view()), name="dashboard"),
    path("logout/", login_required(Logout.as_view()), name="logout"),
    path("otp-verification/", VerifyOtp.as_view(), name="otp_verify"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),
    path("reset-password/", ResetPasswordView.as_view(), name="resetpassword"),
    path("resend/", ResendOtp.as_view(), name="resend-otp"),
    path('password/change/', login_required(ChangePassword.as_view()),
         name='change-password'),
    path('simple-login/', UserLoginView.as_view(), name="simple-login"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from base.views import Login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', never_cache(Login.as_view()), name="login"),
    path('', include('base.urls', namespace='base')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/',include('products.urls', namespace='products')),
    path('utils/', include('utils.urls', namespace='utils')),
    path('inventry/', include('inventry.urls', namespace='inventry')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    path('dhl/', include('dhl_api.urls', namespace='dhl_api')),
    path('inward/', include('inward.urls', namespace='inward')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),  #add the robots.txt file
    
]

# Static files Setup
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
                     Dashboard, CreateOrders, OrderList,
                     SingelOrderView, ChangeDispatchStatusOfOrderOfChild,
                     ChangeDeliveryStatus, OrderDispatchProcess, ExportDispatchNote, AddLRNo,
                     ChangeOrderConfirmationStatus, OrderOfProductCancleation, ExportData, OrdersReport, OrdersCustomReportResponse,
                     OrderSearch, TrackLR
                    )

from orders.api import (CreateOrderApi,)

app_name = "orders"

urlpatterns = [
    path("dashboard",login_required(Dashboard.as_view()), name="orders-dashboard"),
    path("<slug:id>/create-orders",login_required(CreateOrders.as_view()), name="orders-create"),
    path("orders-list",login_required(OrderList.as_view()), name="orders-list"),
    path("<slug:id>/order-details",login_required(SingelOrderView.as_view()), name="order-details"),
    path("<slug:id>/change-dispatch-status/",login_required(ChangeDispatchStatusOfOrderOfChild.as_view()), name="change-order-dispatch-status"),
    path("<slug:id>/change-delivery-status/",login_required(ChangeDeliveryStatus.as_view()), name="change-order-delivery-status"),
    path("<slug:id>/order-dispatch-process",login_required(OrderDispatchProcess.as_view()), name="order-dispatch-process"),
    path("<slug:id>/order-dispatch-note",login_required(ExportDispatchNote.as_view()), name="order-dispatch-note"),
    path("pending-lr-details", login_required(AddLRNo.as_view()), name='pending-lr-details'),
    path("<slug:id>/change-order-confirmation", login_required(ChangeOrderConfirmationStatus.as_view()), name='change-order-confirmation'),
    path("<slug:id>/order-of-item-cancle", login_required(OrderOfProductCancleation.as_view()), name='order-item-cancle'),
    path("export-report/", login_required(ExportData.as_view()), name='export-report'),
    path("report/", login_required(OrdersReport.as_view()), name='orders-report'),
    path("search-report/", login_required(OrdersCustomReportResponse.as_view()), name='search-report'),
    path("search/", login_required(OrderSearch.as_view()), name='search-orders'),
    path("<slug:id>/track-lr", login_required(TrackLR.as_view()), name='track-lr'),

    # api
    path("create-order/",CreateOrderApi.as_view(), name="create-order"),

    
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (ProductList, CreateProduct, 
                    ProductEditView, ProductProperty, 
                    RemoveProductProperty, Dashboard,
                    RemoveProductCategory, CreateCategories,
                    GetProductName, CreateQuality, BomItemList,
                    SingelBom, CategoryWiseList, ExportData, 
                    CreatBOM, SingleProduct, SingleProductByPartNo, 
                    ProductSearch, ProductDetails, SearchBom,
                    DeleteBom, DeleteBomOfChildPart, GetFinishedGoods
                    
                    )

app_name = "products"

urlpatterns = [
    path("list",login_required(ProductList.as_view()), name="products-list"),
    path("dashboard",login_required(Dashboard.as_view()), name="products-dashboard"),
    path("create",login_required(CreateProduct.as_view()), name="products-create"),
    path("<slug:id>/edit",login_required(ProductEditView.as_view()), name="products-edit"),
    path("<slug:id>/product-name",login_required(GetProductName.as_view()), name="products-name"),
    path("<int:id>/product-property/",
         login_required(ProductProperty.as_view()), name="product-property"),
    path("remove-property/", login_required(RemoveProductProperty.as_view()),
         name="remove-property"),
    path("product-category",
         login_required(CreateCategories.as_view()), name="product-category"),
    path("remove-category/", login_required(RemoveProductCategory.as_view()),
         name="remove-category"),
    path("product-quality/", login_required(CreateQuality.as_view()),
         name="product-quality"),
    path("bom-list/", login_required(BomItemList.as_view()),
         name="bom-list"),
    path("<slug:id>/bom", login_required(SingelBom.as_view()),
         name="product-bom"),
    path("<slug:id>/list-product", login_required(CategoryWiseList.as_view()),
         name="category-product"),
    path("product-export",login_required(ExportData.as_view()), name="product-export"),
    path("create-bom/",login_required(CreatBOM.as_view()), name="bom-create"),
    path("<slug:id>/single-product", login_required(SingleProduct.as_view()),
         name="single-product"),
    path("<slug:id>/single-product-part-no", login_required(SingleProductByPartNo.as_view()),
         name="single-product-part-no"),
    path("search/", login_required(ProductSearch.as_view()),
         name="product-search"),
    path("<slug:id>/details", login_required(ProductDetails.as_view()),
         name="product-details"),
    path("search-bom/", login_required(SearchBom.as_view()), name="bom-search"),
    path("<slug:id>/delete-bom/",login_required(DeleteBom.as_view()), name="bom-delete"),
    path("<slug:id>/delete-bom-child/",login_required(DeleteBomOfChildPart.as_view()), name="child-part-delete"),
    path("finished-goods/",login_required(GetFinishedGoods.as_view()), name="finished-goods"),

#     path("<slug:id>/add-vendor", login_required(AddVendorOfProduct.as_view()), name="add-vendor-of-product"),
]

purchase/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from purchase.views import (MRP, Dashboard, CreatePurchaseOrder, 
                            OrderAgainstMRP, PoList, SingelPurchaseOrder, ExportPO, DeletePoProduct,GetPO)



app_name = "purchase"

urlpatterns = [
    
    path("mrp/",login_required(MRP.as_view()), name="purchase-mrp"),
    path("order-mrp/",login_required(OrderAgainstMRP.as_view()), name="purchase-order-mrp"),
    path("dashboard/",login_required(Dashboard.as_view()), name="purchase-dashboard"),
    path("create-po/",login_required(CreatePurchaseOrder.as_view()), name="purchase-order"),
    path("list/",login_required(PoList.as_view()), name="purchase-order-list"),
    path("<slug:product>/create-po/",login_required(CreatePurchaseOrder.as_view()), name="purchase-order"),
    path("<slug:id>/po/",login_required(SingelPurchaseOrder.as_view()), name="purchase-singel-order"),
    path("<slug:id>/remove-product/",login_required(DeletePoProduct.as_view()), name="remove-product-of-po"),
    path("export/<slug:id>/po/",login_required(ExportPO.as_view()), name="export-purchase-singel-order"),
    path("<slug:po>/get-po",login_required(GetPO.as_view()), name="get-po"),

]

vendors/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (CreateVendor, VendorList, VendorEditView,
                    VendorDelete, Dashboard, GetVenderName,
                    CreateCategories, RemoveVendorCategory, VendorDetails,
                    SearchVendor, DeleteVendorOfProduct, VendorOfProduct,
                    ProductByVendor
                    )

app_name = "vendors"

urlpatterns = [
    path("create/", login_required(CreateVendor.as_view()),
         name="vendor-create"),
    path("list/", login_required(VendorList.as_view()),
         name="vendor-list"),
    path("<slug:id>/edit/", login_required(VendorEditView.as_view()),
         name="vendor-edit"),
    path("<slug:id>/delete/", login_required(VendorDelete.as_view()),
         name="vendor-delete"),
    path("dashboard",login_required(Dashboard.as_view()), name="vendor-dashboard"),
    path("<slug:id>/get-vendor-name",login_required(GetVenderName.as_view()), name="vendor-get-name"),
    path("vendor-category",
         login_required(CreateCategories.as_view()), name="vendor-category"),
    path("remove-category/", login_required(RemoveVendorCategory.as_view()),
         name="remove-category"),
    path("<slug:id>/vendor-details/", login_required(VendorDetails.as_view()), name="vendor-details"),
    path("<slug:id>/vendor-of-product/delete", login_required(DeleteVendorOfProduct.as_view()), name="delete-vendor-product"),
    path("search/", login_required(SearchVendor.as_view()),
         name="vendor-search"),
    path("<slug:id>/vendor-of-product/", login_required(VendorOfProduct.as_view()),
         name="vendor-product"),
    path("product-of-vendors/", login_required(ProductByVendor.as_view()),
         name="product-by-vendors"), 
]

purchase/models.py
from django.db import models

from products.models import Product, Categories
from vendors.models import Vendor
from base.models import Base

from purchase.managers import PurchaseOrderManager


# Create your models here.

class TaxCode(Base):
    name = models.CharField(max_length=150, blank=True, null=True) 
    code= models.CharField(max_length=30, blank=True, null=True)
    value =  models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return str(self.name)

class PaymentTerms(Base):
    name = models.CharField(max_length=150, blank=True, null=True) 
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.name)


class TermsAndConditions(Base):
    name = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.name)



class PurchaseOrder(Base):
    po_no = models.CharField(max_length=30, blank=True, null=True) # autogenrated
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True,null=True)
    vendor = models.ForeignKey(
        Vendor, on_delete=models.CASCADE)
    tax_code = models.ManyToManyField(TaxCode, blank=True)
    general_terms = models.ManyToManyField(TermsAndConditions, blank=True)
    payment_term = models.ForeignKey(PaymentTerms, on_delete=models.CASCADE, blank=True, null=True)
    status = models.BooleanField(default=True)
    del_date = models.DateTimeField(blank=True, null=True)
    total = models.DecimalField(max_digits=12,decimal_places=2, default=0)
    with_tax_total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    checked_by = models.IntegerField(null=True, blank=True)
    remarks = models.TextField(blank=True, null=True)
    close_date = models.DateTimeField(blank=True, null=True)
    gl_name = models.ForeignKey(Categories, on_delete=models.CASCADE, blank=True,null=True)

    objects = PurchaseOrderManager()

    def __str__(self):
        return str(self.vendor.comany_name)


class PurchaseItem(Base):
    po = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    part = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.DecimalField(max_digits=12, decimal_places=4)
    del_date = models.DateTimeField(blank=True, null=True)
    price = models.DecimalField(max_digits=12,decimal_places=2, default=0)
    status = models.BooleanField(default=False)
    recived_qty = models.DecimalField(max_digits=12, decimal_places=4, default=0)

    def __str__(self):
        return str(self.part.name)
    

inward/forms.py
from datetime import date, datetime

from django import forms

from products.models import Product
from vendors.models import Vendor
from utils.constants import StockTransection

class InWardForm(forms.Form):
    po_no = forms.CharField(required=True, label="Purchase No", widget=forms.TextInput(
        attrs={"class": "form-control"}))
    bill_no = forms.CharField(required=True, label="Invoice/Challan No", widget=forms.TextInput(
        attrs={"class": "form-control"}))
    bill_date = forms.CharField(required=True, label="Invoice/Challan Date", widget=forms.DateInput(
        attrs={"class": "form-control","type":"date"}))
    
    remarks = forms.CharField(required=False, label="Remarks", widget=forms.Textarea(
        attrs={"class": "form-control aiz-text-editor", "rows": "5"}))
    file_url = forms.FileField(required=False, label="Bill PDF", widget=forms.FileInput(attrs={'class': "form-control", 'accept': "PDF"}), help_text="Please upload only .PDF file")
    

    def __init__(self, *args, **kwargs):
        self.user = None
        super(InWardForm, self).__init__(*args, **kwargs)

    def clean_bill_date(self):
        input_date = datetime.strptime(self.cleaned_data.get("bill_date"), '%Y-%m-%d')

        if input_date > datetime.combine(date.today(), datetime.min.time()):
            raise forms.ValidationError(' Invoice date cannot be in the future.')
        else:
            return input_date 


# Stock
class StockForm(forms.Form):
    part_no = forms.CharField(required="False", label="Part No.", widget=forms.TextInput(
        attrs={"class": "form-control","id":"part-no"}))
    parts = forms.ModelChoiceField(queryset=Product.objects.active(), widget=forms.Select(
        attrs={"class": "form-control form-select","autofocus":True, "id":"parts"}), required=True, label="Part No.", empty_label='--- Select Product ---')
    transection_type = forms.ChoiceField(required=True, label="Transection Type", choices=StockTransection.choices(
    ), widget=forms.Select(attrs={"class": "form-control form-select"}))
    receive_by = forms.CharField(required=True, label="Receive By", widget=forms.TextInput(
        attrs={"class": "form-control"}))
    qty = forms.CharField(required=True, label="Issued Qty", widget=forms.NumberInput(
        attrs={"class": "form-control"}))

    def __init__(self, *args, **kwargs):
        self.user = None
        super(StockForm, self).__init__(*args, **kwargs)

purchase/forms.py
from datetime import date, datetime

from django import forms
from django.core.validators import validate_email

from products.models import (Unit, Product)
from vendors.models import Vendor

purchase/templates/purchase/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}PO{% endblock %}

{% block css %}

{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
        href="{% url 'products:products-list' %}">Purchase</a> / <b class="text-dark">PO<b></li>
{% endblock %}

{% block head %}
Purchase Order
{% endblock %}

{% block content %}
<style>
    table, th, td {
        border: 1px solid;
      }
</style>
<div class="row">
    <div class="col-md-12 mt-3">
        <div class="card mb-4">
          <h5 class="card-header">New PO</h5>
          <div class="card-body">
                <form class="mt-3 " method="post" enctype="multipart/form-data" action='.' data-url='{{ request.build_absolute_uri|safe }}' id="create-product">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="mb-3 col-2 ">
                                    <label class="form-label" for="basic-default-inword-bill_no">PO No:</label>
                                    <span class="text-danger"></span>
                                    <input type="text" class="form-control" name="po_no" value="{{po_no}}" required>
                                    <span class="text-danger print_error" id="code"></span>
                                </div>
                                <div class="mb-3 col-2">
                                    <label class="form-label" for="basic-default-inword-bill_no">Item:</label>
                                    <span class="text-danger"></span>
                                    <input type="text" id="id_part_no" class="form-control" value="{{product.part_no}}" required>
                                    <span class="text-danger print_error" id="code"></span>
                                </div>

                                <div class="mb-3 col-4">
                                    <label class="form-label" for="basic-default-inword-bill_no">Indent:</label>
                                    <span class="text-danger"></span>
                                    <input type="text" name="indent" id="id_part_no" class="form-control" placeholder=" * If Indent then Po No.">
                                    <span class="text-danger print_error" id="code"></span>
                                </div>
                                
                                <div class="mb-3 col-4">
                                    <label class="form-label" for="basic-default-inword-bill_no">Payment Terms:</label>
                                    <span class="text-danger"></span>
                                    <select class="form-select" id="inputGroupSelect01" name="payment_term">
                                        <option value="0" selected>Choose...</option>
                                        {% for term in payment_term %}
                                        <option value={{term.id}}>{{term}}</option>
                                        {% endfor %}
                                      </select>
                                </div>
                                <div class="mb-3 col-12">
                                    <label class="form-label" for="basic-default-inword-bill_no">Remark:</label>
                                    <span class="text-danger"></span>
                                    <textarea name="remark" cols="40" rows="5" class="form-control aiz-text-editor" id="id_description"></textarea>
                                    <span class="text-danger print_error" id="code"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3">
                                <h5>Vendor List</h5>
                                <table class="">
                                    <tr>
                                        <th>No.</th>
                                        <th>Select</th>
                                        <th>Vendor Name</th>
                                        <th>Part No</th>
                                        <th>Description</th>
                                        <th>Rate</th>
                                    </tr>
                                    <tbody id="vendor-list-by-product">
                                    {% for i in vendors %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td><input name="vendor" class="form-check-input" type="radio" value="{{i.vendor.id}}" id="vendor"></td>
                                        <td><a href="javascript:void(0);" onclick='openVendor("{% url 'vendors:vendor-details' i.vendor.id %}")' >{{i.vendor.comany_name|upper}}</a></td>
                                        <td>{{i.product.part_no}}</td>
                                        <td>{{i.product.name}}</td>
                                        <td><i class="fa fa-inr" aria-hidden="true"></i> {{i.price}} / {{i.product.umo}}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                    
                                </table>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mb-3">
                                <h5>Other Product Suggestion</h5>
                                <div id="id_vendorsof_product_list">

                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div classs="row">
                        <div class="col-12">
                            <button class="btn btn-success mt-5 " type="submit" style="float:right">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/jquery.form.js'%}"></script>

<script>
    $(document).ready(function () {
        var $myForm = $('#create-product')
        $myForm.on("submit", function (event) {
            event.preventDefault()
            var formData = $(this).serialize()
            var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
            option = {
                method: "POST",
                url: $thisURL,
                data: formData,
                success: function (data) {
                    if (data.error) {
                        var message = "<div class='bs-toast toast fade show bg-{{message.tags}} toast-placement-ex m-2 top-0 end-0' role='alert' aria-live='assertive' aria-atomic='true' style='float:right'>" +
                            "<div class='toast-header bg-danger'>" +
                            "<strong class='mr-auto text-white'>Error</strong>" +
                            "<button type='button' class='ml-2 mb-1 close' data-dismiss='toast'>&times;</button>" +
                            "</div><div class='toast-body'>Error Occurred, Product Code was already stored" +
                            "</div></div>";
                        $("#error-message").html(message);
                        $('.toast').toast('show');
                    }
                    else {
                        location.replace(data.url)
                    }

                },
                error: function (data) {
                    $(".print_error").text("")
                    $("#code").text("")
                    $("#image").text("")
                    $(".print_error").text()
                    $("#code").text(data.responseJSON.code)
                    $("#image").text(data.responseJSON.image)
                    $("#image").text(data.responseJSON.exception)
                },
            }
            $myForm.ajaxSubmit(option)
        })
    })
</script>

<script>
    // Get all radio buttons in the group
    const radioButtons = document.querySelectorAll('input[name="vendor"]');

    // Add change event listener to the radio button group
    radioButtons.forEach(radioButton => {
        radioButton.addEventListener('change', function() {
            // Handle the change event
            const selectedVendor = this.value;
            console.log(selectedVendor)
            $('#id_vendorsof_product_list').html("");
            $.ajax({
                url: "{{product_url}}"+ selectedVendor +"/vendor-of-product/",
                type: 'GET',
                //data: { 'query': query},
                success: function (data) {
                  console.log(data)
                    $('#id_vendorsof_product_list').html(data.data);
                }
            });
        });
    });
</script>

<script>
    $(document).on("keyup", "#id_part_no", function () {
      var id = this.value;
      // var category = $()
      $('#vendor-list-by-product').html("");
      $('#id_vendorsof_product_list').html("");
      $.ajax({
          url: "{% url 'vendors:product-by-vendors' %}",
          type: 'GET',
          data: { 'query': id},
          success: function (data) {
            console.log(data)
              $('#vendor-list-by-product').html(data.data);
          }
      });
  });
</script>

<script>
    $('#purchase-menu').addClass('active open');
    $('#purchase-order-create').addClass('active')
</script>

<script>
    function openVendor(url) {
        const newWindow = window.open(url, 'pop', 'width=1200,height=600');
        if (newWindow) {
            return false;
        }
    }
</script>
{% endblock %}

purchase/templates/purchase/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load product_extras %}

{% block title %}Purchase{% endblock %}

{% block css %}

{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
  href="{% url 'purchase:purchase-dashboard' %}"><b class="text-dark">Purchase</b></a> 
{% endblock %}

{% block head %}
Dashboard
{% endblock %}

{% block content %}
<div class="col-lg-12 col-md-6 mt-4">
  <div class="card">
    <div class="row row-bordered g-0">
      <div class="col-md-12">
        <h5 class="card-header m-0 me-2 pb-3"> Month Wise Product Sales</h5>
        {{monthly_sales}}
      </div>
      
      <table class="table table-sm table-bordered">
        <tr>
          <th>No</th>
          <th>Code</th>
          <th>Name</th>
          <th>Stock</th>
          <th>MSL</th>
          
          
        </tr>
        {% for i in products %}
        <tr>
          <td> {{forloop.counter}} </td>
          <th> {{i.part_no}} </th>
          <th> {{i.name}} </th>
          <th> {{i.stock}} </th>
          <th> {{i.minimum_stock_level}} </th>
          
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>


{% endblock content %}

{% block js %}
<script>
  $('#purchase-menu').addClass('active open');
  $('#purchase-dashboard').addClass('active')
</script>
{% endblock js %}