base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (UserRegister,
                    Logout,
                    VerifyOtp,
                    Dashboard,
                    ResetPasswordView,
                    ForgotPasswordView,
                    ResendOtp, ChangePassword
                    )

from base.api import UserLoginView

app_name = "base"

urlpatterns = [
    # path("register/", UserRegister.as_view(), name="register"),
    path("dashboard/", login_required(Dashboard.as_view()), name="dashboard"),
    path("logout/", login_required(Logout.as_view()), name="logout"),
    path("otp-verification/", VerifyOtp.as_view(), name="otp_verify"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),
    path("reset-password/", ResetPasswordView.as_view(), name="resetpassword"),
    path("resend/", ResendOtp.as_view(), name="resend-otp"),
    path('password/change/', login_required(ChangePassword.as_view()),
         name='change-password'),
    path('simple-login/', UserLoginView.as_view(), name="simple-login"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from base.views import Login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', never_cache(Login.as_view()), name="login"),
    path('', include('base.urls', namespace='base')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/',include('products.urls', namespace='products')),
    path('utils/', include('utils.urls', namespace='utils')),
    path('inventry/', include('inventry.urls', namespace='inventry')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    path('dhl/', include('dhl_api.urls', namespace='dhl_api')),
    path('inward/', include('inward.urls', namespace='inward')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),  #add the robots.txt file
    
]

# Static files Setup
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventry/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
                    Dashboard, ExportData, 
                    SimpleAddStock, StockHistoryInJson, StockHistoriesList, 
                    InventryReport, InventryReportStock, FinishedAddStock)

app_name = "inventry"

urlpatterns = [
    path("dashboard",login_required(Dashboard.as_view()), name="inventry-dashboard"),
    path("add-stock/", login_required(SimpleAddStock.as_view()), name="add-stock"),
    path("finished-add-stock/", login_required(FinishedAddStock.as_view()), name="finished-add-stock"),
    path("<slug:id>/stock-history/", login_required(StockHistoryInJson.as_view()), name="json-stock-history"),
    path("stock-history/", login_required(StockHistoriesList.as_view()), name="stock-histories"),
    path("reports/", login_required(InventryReport.as_view()), name="stock-report"),
    path("export-report/",login_required(ExportData.as_view()), name="export-today"),
    path("search-report/",login_required(InventryReportStock.as_view()), name="search-report"),

]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (ProductList, CreateProduct, 
                    ProductEditView, ProductProperty, 
                    RemoveProductProperty, Dashboard,
                    RemoveProductCategory, CreateCategories,
                    GetProductName, CreateQuality, BomItemList,
                    SingelBom, CategoryWiseList, ExportData, 
                    CreatBOM, SingleProduct, SingleProductByPartNo, 
                    ProductSearch, ProductDetails, SearchBom,
                    DeleteBom, DeleteBomOfChildPart, GetFinishedGoods
                    
                    )

app_name = "products"

urlpatterns = [
    path("list",login_required(ProductList.as_view()), name="products-list"),
    path("dashboard",login_required(Dashboard.as_view()), name="products-dashboard"),
    path("create",login_required(CreateProduct.as_view()), name="products-create"),
    path("<slug:id>/edit",login_required(ProductEditView.as_view()), name="products-edit"),
    path("<slug:id>/product-name",login_required(GetProductName.as_view()), name="products-name"),
    path("<int:id>/product-property/",
         login_required(ProductProperty.as_view()), name="product-property"),
    path("remove-property/", login_required(RemoveProductProperty.as_view()),
         name="remove-property"),
    path("product-category",
         login_required(CreateCategories.as_view()), name="product-category"),
    path("remove-category/", login_required(RemoveProductCategory.as_view()),
         name="remove-category"),
    path("product-quality/", login_required(CreateQuality.as_view()),
         name="product-quality"),
    path("bom-list/", login_required(BomItemList.as_view()),
         name="bom-list"),
    path("<slug:id>/bom", login_required(SingelBom.as_view()),
         name="product-bom"),
    path("<slug:id>/list-product", login_required(CategoryWiseList.as_view()),
         name="category-product"),
    path("product-export",login_required(ExportData.as_view()), name="product-export"),
    path("create-bom/",login_required(CreatBOM.as_view()), name="bom-create"),
    path("<slug:id>/single-product", login_required(SingleProduct.as_view()),
         name="single-product"),
    path("<slug:id>/single-product-part-no", login_required(SingleProductByPartNo.as_view()),
         name="single-product-part-no"),
    path("search/", login_required(ProductSearch.as_view()),
         name="product-search"),
    path("<slug:id>/details", login_required(ProductDetails.as_view()),
         name="product-details"),
    path("search-bom/", login_required(SearchBom.as_view()), name="bom-search"),
    path("<slug:id>/delete-bom/",login_required(DeleteBom.as_view()), name="bom-delete"),
    path("<slug:id>/delete-bom-child/",login_required(DeleteBomOfChildPart.as_view()), name="child-part-delete"),
    path("finished-goods/",login_required(GetFinishedGoods.as_view()), name="finished-goods"),

#     path("<slug:id>/add-vendor", login_required(AddVendorOfProduct.as_view()), name="add-vendor-of-product"),
]

products/views.py
import os
import json
from csv import DictReader
from io import TextIOWrapper

from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import View
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, Http404
from django.template.loader import render_to_string
from django.core.files.storage import default_storage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import (Product, Attribute, ProductAttribute,
                      Categories, PartQuality, BOMItem, SubCategory
                    )
from .forms import ProductForm, FileUploadForm
from utils.views import get_secured_url, is_ajax
from .serializers import InwordOfProductSerializer, ProductSerializer, ProductSerializerWithId
from utils.views import generate_part_code, BarCode
from .resources import ProductResource
from vendors.models import Vendor


# Product Dashboard
class Dashboard(View):
    template_name = "products/dashboard.html"

    def get(self, request):
        total_categories = Categories.objects.all()
        total_product = Product.objects.active().count()
        __item = {}
        for i in total_categories:
           __item[i.name] = Product.objects.category_by_count(i)
        context = {
            "total":total_product,
            "category_by":__item,
            "categories":total_categories
        }

        # product_a = Product.objects.get(code="FLBGC01")
        # bom = product_a.get_bom()
        # Print the BOM
        # for component, quantity in bom.items():
        #     print(f"Component: {component}, Quantity: {quantity}")

        return render(request,self.template_name, context)


# Product List
class ProductList(View):
    template_name = "products/list.html"

    def get(self,request):
        categories = Categories.objects.all()
        products = Product.objects.active()
        results_per_page = 7
        page = request.GET.get('page', 1)
        paginator = Paginator(products, results_per_page)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context = {
            "products": products,
            "data" : [page,results_per_page],
            "categories":categories

        }
        return render(request, self.template_name, context)

    

# Product Create.
class CreateProduct(FormView):
    form_class = ProductForm
    template_name = "products/create.html"
    success_url = "/products/list/"

    def form_invalid(self, form):
        response = super(CreateProduct, self).form_invalid(form)
        if is_ajax(self.request):
            data = form.errors
            return JsonResponse(data, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super(CreateProduct, self).form_valid(form)        
        try:
            if is_ajax(self.request):
                form_data = form.cleaned_data
                with transaction.atomic():
                    
                    if Categories.objects.get(slug="finish-goods") == form_data["category"]  and Product.objects.filter(code=form_data['code']).exists():
                        data = {"error": "Product Was already stored.", "status": 403}
                        return JsonResponse(data)
                    else:
                        product = Product()
                        product.code = form_data['code']
                        product.name = form_data['name']
                        product.category = form_data["category"]
                        product.description = form_data['description']
                        product.umo = form_data['umo']
                        product.specification = form_data['specification']
                        product.stock = form_data['stock']
                        product.minimum_stock_level  = form_data['minimum_stock_level']
                        product.rack_no = form_data['rack_no']
                        product.tray_no = form_data['tray_no']
                        product.created_by = self.request.user.id
                        product.quality_type = form_data['part_quality']
                        product.version = form_data['part_version']                    
                        product.save()

                        product.part_no = generate_part_code(product.id, product.version, product.quality_type.code)
                        product.save()

                    if form_data['image']:
                        product.save_image_url(form_data["image"], get_secured_url(
                                self.request) + self.request.META["HTTP_HOST"])
                        
                    gen_barcode = BarCode()
                    path = "products/"+ product.part_no + "/barcodes/"
                    status = gen_barcode.generate(product.part_no,product.part_no,path, product.name + ".png")
                    product.barcode_image = get_secured_url(self.request) + self.request.META["HTTP_HOST"] +"/media/" + path + product.name + ".png"
                    product.save()
                    
                    messages.success(
                        self.request, "Product added successfully.")
                data = {
                        'message': "Product added successfully.",
                        'url': get_secured_url(
                            self.request) + self.request.META["HTTP_HOST"] + '/products/' + str(product.id) + '/product-property/'
                    }
                return JsonResponse(data)
            else:
                return response
        
        except Exception as e:
            data = {"error": str(e), "status": 403}
            return JsonResponse(data)


#Product Edit
class ProductEditView(FormView):
    form_class = ProductForm
    template_name = "products/edit.html"

    def get_form_kwargs(self):
        product = Product.objects.single_product(
            id= self.kwargs["id"])
        kwargs = super(ProductEditView, self).get_form_kwargs()
        kwargs.update({"product": product, "edit": True})
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super(ProductEditView, self).get_context_data(**kwargs)
        product = Product.objects.single_product(id=self.kwargs["id"])
        context['product'] = product
        context['previous_url'] = self.request.META.get('HTTP_REFERER')
        return context
    
    def form_invalid(self, form):
        super(ProductEditView, self).form_invalid(form)
        messages.error(self.request,form.errors)
        return redirect(self.request.META['HTTP_REFERER'])
    
    def form_valid(self, form):
        form_data = form.cleaned_data
        try:
            with transaction.atomic():
                product = Product.objects.single_product(id = self.kwargs['id'])
                if product.code != form_data['code']:
                    product.code = form_data['code']
                if product.name != form_data['name']:
                    product.name = form_data['name']
                if product.category != form_data['category']:
                    product.category = form_data['category']
                if product.description != form_data['description']:
                    product.description = form_data['description']
                if product.umo != form_data['umo']:
                    product.umo = form_data['umo']
                if product.specification != form_data['specification']:
                    product.specification = form_data['specification']
                if product.stock != form_data['stock']:
                    product.stock = form_data['stock']
                if product.minimum_stock_level != form_data['minimum_stock_level']:
                    product.minimum_stock_level = form_data['minimum_stock_level']
                if product.rack_no != form_data['rack_no']:
                    product.rack_no = form_data['rack_no']
                if product.tray_no != form_data['tray_no']:
                    product.tray_no = form_data['tray_no']
                product.updated_by = self.request.user.id
                product.save()
                if form_data['image']:
                    if product.image:
                        old_image = '/'.join(product.image.split('/')[4:])
                        if default_storage.exists(old_image):
                            default_storage.delete(old_image)
                    product.save_image_url(form_data["image"], get_secured_url(
                            self.request) + self.request.META["HTTP_HOST"])
                return redirect('products:products-list')
            
        except Exception as e:
            messages.error(self.request, str(e))
            return redirect(self.request.META['HTTP_REFERER'])


class ProductProperty(View):
    template_name = "products/attribute.html"

    def get(self, request, id):
        product = Product.objects.single_product(id)
        properties = ProductAttribute.objects.filter(product=product)
        attribute = Attribute.objects.all()
        previous_url = request.META.get('HTTP_REFERER')
        context = {
            "product": product,
            "properties": properties,
            "previous_url": previous_url,
            "attribute": attribute
        }

        return render(request, self.template_name, context)

    def post(self, request, id):
        product = Product.objects.single_product(id)
        try:
            data = json.loads(request.POST.get("data"))
            if data["attribute"] != '' and data["value"] != '':
                attribute = data["attribute"]
                value = data["value"].strip()
                obj, created = Attribute.objects.get_or_create(

products/templates/warehouse/list.html
{% extends "base.html" %}
{% load static %}
{% load product_extras %}

{% block title %}Finished Goods{% endblock %}

{% block css %}
<style>
  /* Style for the modal */
  .modal {
    display: none;
  }

  /* Style for the modal content */
  .modal-content {
    max-width: 80%;
    max-height: 80%;
    overflow: hidden;
    background-color: #fff; /* Background color for the modal content */
    position: relative;
    text-align: center;
    border-radius: 8px;
  }

  /* Style for the close button */
  .close {
    position: absolute;
    top: 10px;
    right: 10px;
    color: #000;
    cursor: pointer;
    font-size: 20px;
  }
</style>
{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
  href="{% url 'products:products-list' %}">Products</a> / <b class="text-dark">Finished Goods<b></li>
{% endblock %}

{% block head %}
Finished Goods
{% endblock %}

{% block content %}

<div class="container-fluid mt-3 mb-5">
  <div class="row">
    <div class="col-4">
      <div class="input-group">
        <label class="input-group-text" for="inputGroupSelect01">Categories</label>
        <select class="form-select" id="inputGroupSelect01">
          <option value="0" selected>Choose...</option>
          {% for category in categories %}
          <option value={{category.id}}>{{category.name}}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <div class="col-4">
      <input type="text" class="form-control mb-2" id="id_search" name="search" placeholder="Search" />
      
    </div>
    <div class="col-4">
      <a class="btn btn-success fl-end" href="{% url 'inventry:finished-add-stock' %}">Add Stock</a>
    </div>
    
    <div class="col-12">

      <!-- Basic Bootstrap Table -->
      <div class="card">
        
        
        {% comment %} <a class="btn btn-success col-1">Add New</a> {% endcomment %}
        <div class="table-responsive text-nowrap" id="id_products_list">
          <table class="table">
            <thead>
              <tr>
                <th>No</th>
                {% comment %} <th>Code</th> {% endcomment %}
                
                <th>Code</th>
                <th>Name</th>
                <th>UOM</th>
                <th>Stock</th>
                <th>Action</th>
              </tr>
              
            </thead>
            <tbody class="table-border-bottom-0">
              {% for product in products %}
              <tr >
                <td>
                {{ forloop.counter|adjust_for_pagination:data }}
                </td>
                
                <td><a href="{% url "products:product-details" product.part_no %}">{{product.code}}</a></td>
                <td>{{product.name}}</td>
                <td> {{product.umo}} </td>
                {% if product.stock < product.minimum_stock_level %}
                <td class="bg-danger"> 
                  {% else %}
                  <td> 
                {% endif %}
                {{product.stock}} </td>
                <td>
                  <a href="{% url 'products:products-edit' product.id %}" class="btn btn-primary btn-circle "
                                title="Product Edit"><i class="fas fa-edit" aria-hidden="true"></i></a>
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
          
        </div>
        
      </div>
      <!--/ Basic Bootstrap Table -->
    </div>
  </div>
  <div class="row container-fluid mt-2">
 
    {% if products.paginator.num_pages > 1 %}    
    {% include 'components/pagination.html' with items=products paginator=products.paginator %}
    {% endif %}
</div>
</div>
<div class="mt-5"></div>

<!-- The Modal -->
<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <!-- Modal content -->
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <!-- Close button -->
      <button type="button" class="btn-close close" data-bs-dismiss="modal" aria-label="Close"></button>
      <!-- Image container -->
      <img id="modalImage" src="" alt="Modal Image" style="width: 100%; height: 100%;">
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
<script>
  $('#ware-house').addClass('active open');
  $('#finished').addClass('active')
</script>

<script>
  $(document).on("keyup", "#id_search", function () {
    var select = document.getElementById("inputGroupSelect01");
    var selectedOption = select.options[select.selectedIndex];
    var selectedValue = selectedOption.value;
    
    var query = this.value;
    // var category = $()
    $.ajax({
        url: '/products/search/',
        type: 'GET',
        data: { 'query': query, "category":selectedValue},
        success: function (data) {
            $('#id_products_list').html(data.data);
        }
    });
});
</script>
{% endblock js %}