base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (UserRegister,
                    Logout,
                    VerifyOtp,
                    Dashboard,
                    ResetPasswordView,
                    ForgotPasswordView,
                    ResendOtp, ChangePassword
                    )

from base.api import UserLoginView

app_name = "base"

urlpatterns = [
    # path("register/", UserRegister.as_view(), name="register"),
    path("dashboard/", login_required(Dashboard.as_view()), name="dashboard"),
    path("logout/", login_required(Logout.as_view()), name="logout"),
    path("otp-verification/", VerifyOtp.as_view(), name="otp_verify"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),
    path("reset-password/", ResetPasswordView.as_view(), name="resetpassword"),
    path("resend/", ResendOtp.as_view(), name="resend-otp"),
    path('password/change/', login_required(ChangePassword.as_view()),
         name='change-password'),
    path('simple-login/', UserLoginView.as_view(), name="simple-login"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from base.views import Login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', never_cache(Login.as_view()), name="login"),
    path('', include('base.urls', namespace='base')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/',include('products.urls', namespace='products')),
    path('utils/', include('utils.urls', namespace='utils')),
    path('inventry/', include('inventry.urls', namespace='inventry')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    path('dhl/', include('dhl_api.urls', namespace='dhl_api')),
    path('inward/', include('inward.urls', namespace='inward')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),  #add the robots.txt file
    
]

# Static files Setup
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (ProductList, CreateProduct, 
                    ProductEditView, ProductProperty, 
                    RemoveProductProperty, Dashboard,
                    RemoveProductCategory, CreateCategories,
                    GetProductName, CreateQuality, BomItemList,
                    SingelBom, CategoryWiseList, ExportData, 
                    CreatBOM, SingleProduct, SingleProductByPartNo, 
                    ProductSearch, ProductDetails, SearchBom,
                    DeleteBom, DeleteBomOfChildPart, GetFinishedGoods
                    
                    )

app_name = "products"

urlpatterns = [
    path("list",login_required(ProductList.as_view()), name="products-list"),
    path("dashboard",login_required(Dashboard.as_view()), name="products-dashboard"),
    path("create",login_required(CreateProduct.as_view()), name="products-create"),
    path("<slug:id>/edit",login_required(ProductEditView.as_view()), name="products-edit"),
    path("<slug:id>/product-name",login_required(GetProductName.as_view()), name="products-name"),
    path("<int:id>/product-property/",
         login_required(ProductProperty.as_view()), name="product-property"),
    path("remove-property/", login_required(RemoveProductProperty.as_view()),
         name="remove-property"),
    path("product-category",
         login_required(CreateCategories.as_view()), name="product-category"),
    path("remove-category/", login_required(RemoveProductCategory.as_view()),
         name="remove-category"),
    path("product-quality/", login_required(CreateQuality.as_view()),
         name="product-quality"),
    path("bom-list/", login_required(BomItemList.as_view()),
         name="bom-list"),
    path("<slug:id>/bom", login_required(SingelBom.as_view()),
         name="product-bom"),
    path("<slug:id>/list-product", login_required(CategoryWiseList.as_view()),
         name="category-product"),
    path("product-export",login_required(ExportData.as_view()), name="product-export"),
    path("create-bom/",login_required(CreatBOM.as_view()), name="bom-create"),
    path("<slug:id>/single-product", login_required(SingleProduct.as_view()),
         name="single-product"),
    path("<slug:id>/single-product-part-no", login_required(SingleProductByPartNo.as_view()),
         name="single-product-part-no"),
    path("search/", login_required(ProductSearch.as_view()),
         name="product-search"),
    path("<slug:id>/details", login_required(ProductDetails.as_view()),
         name="product-details"),
    path("search-bom/", login_required(SearchBom.as_view()), name="bom-search"),
    path("<slug:id>/delete-bom/",login_required(DeleteBom.as_view()), name="bom-delete"),
    path("<slug:id>/delete-bom-child/",login_required(DeleteBomOfChildPart.as_view()), name="child-part-delete"),
    path("finished-goods/",login_required(GetFinishedGoods.as_view()), name="finished-goods"),

#     path("<slug:id>/add-vendor", login_required(AddVendorOfProduct.as_view()), name="add-vendor-of-product"),
]

products/views.py
import os
import json
from csv import DictReader
from io import TextIOWrapper

from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import View
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, Http404
from django.template.loader import render_to_string
from django.core.files.storage import default_storage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import (Product, Attribute, ProductAttribute,
                      Categories, PartQuality, BOMItem, SubCategory
                    )
from .forms import ProductForm, FileUploadForm
from utils.views import get_secured_url, is_ajax
from .serializers import InwordOfProductSerializer, ProductSerializer, ProductSerializerWithId
from utils.views import generate_part_code, BarCode
from .resources import ProductResource
from vendors.models import Vendor


# Product Dashboard
class Dashboard(View):
    template_name = "products/dashboard.html"

    def get(self, request):
        total_categories = Categories.objects.all()
        total_product = Product.objects.active().count()
        __item = {}
        for i in total_categories:
           __item[i.name] = Product.objects.category_by_count(i)
        context = {
            "total":total_product,
            "category_by":__item,
            "categories":total_categories
        }

        # product_a = Product.objects.get(code="FLBGC01")
        # bom = product_a.get_bom()
        # Print the BOM
        # for component, quantity in bom.items():
        #     print(f"Component: {component}, Quantity: {quantity}")

        return render(request,self.template_name, context)


# Product List
class ProductList(View):
    template_name = "products/list.html"

    def get(self,request):
        categories = Categories.objects.all()
        products = Product.objects.active()
        results_per_page = 7
        page = request.GET.get('page', 1)
        paginator = Paginator(products, results_per_page)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context = {
            "products": products,
            "data" : [page,results_per_page],
            "categories":categories

        }
        return render(request, self.template_name, context)

    

# Product Create.
class CreateProduct(FormView):
    form_class = ProductForm
    template_name = "products/create.html"
    success_url = "/products/list/"

    def form_invalid(self, form):
        response = super(CreateProduct, self).form_invalid(form)
        if is_ajax(self.request):
            data = form.errors
            return JsonResponse(data, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super(CreateProduct, self).form_valid(form)        
        try:
            if is_ajax(self.request):
                form_data = form.cleaned_data
                with transaction.atomic():
                    
                    if Categories.objects.get(slug="finish-goods") == form_data["category"]  and Product.objects.filter(code=form_data['code']).exists():
                        data = {"error": "Product Was already stored.", "status": 403}
                        return JsonResponse(data)
                    else:
                        product = Product()
                        product.code = form_data['code']
                        product.name = form_data['name']
                        product.category = form_data["category"]
                        product.description = form_data['description']
                        product.umo = form_data['umo']
                        product.specification = form_data['specification']
                        product.stock = form_data['stock']
                        product.minimum_stock_level  = form_data['minimum_stock_level']
                        product.rack_no = form_data['rack_no']
                        product.tray_no = form_data['tray_no']
                        product.created_by = self.request.user.id
                        product.quality_type = form_data['part_quality']
                        product.version = form_data['part_version']                    
                        product.save()

                        product.part_no = generate_part_code(product.id, product.version, product.quality_type.code)
                        product.save()

                    if form_data['image']:
                        product.save_image_url(form_data["image"], get_secured_url(
                                self.request) + self.request.META["HTTP_HOST"])
                        
                    gen_barcode = BarCode()
                    path = "products/"+ product.part_no + "/barcodes/"
                    status = gen_barcode.generate(product.part_no,product.part_no,path, product.name + ".png")
                    product.barcode_image = get_secured_url(self.request) + self.request.META["HTTP_HOST"] +"/media/" + path + product.name + ".png"
                    product.save()
                    
                    messages.success(
                        self.request, "Product added successfully.")
                data = {
                        'message': "Product added successfully.",
                        'url': get_secured_url(
                            self.request) + self.request.META["HTTP_HOST"] + '/products/' + str(product.id) + '/product-property/'
                    }
                return JsonResponse(data)
            else:
                return response
        
        except Exception as e:
            data = {"error": str(e), "status": 403}
            return JsonResponse(data)


#Product Edit
class ProductEditView(FormView):
    form_class = ProductForm
    template_name = "products/edit.html"

    def get_form_kwargs(self):
        product = Product.objects.single_product(
            id= self.kwargs["id"])
        kwargs = super(ProductEditView, self).get_form_kwargs()
        kwargs.update({"product": product, "edit": True})
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super(ProductEditView, self).get_context_data(**kwargs)
        product = Product.objects.single_product(id=self.kwargs["id"])
        context['product'] = product
        context['previous_url'] = self.request.META.get('HTTP_REFERER')
        return context
    
    def form_invalid(self, form):
        super(ProductEditView, self).form_invalid(form)
        messages.error(self.request,form.errors)
        return redirect(self.request.META['HTTP_REFERER'])
    
    def form_valid(self, form):
        form_data = form.cleaned_data
        try:
            with transaction.atomic():
                product = Product.objects.single_product(id = self.kwargs['id'])
                if product.code != form_data['code']:
                    product.code = form_data['code']
                if product.name != form_data['name']:
                    product.name = form_data['name']
                if product.category != form_data['category']:
                    product.category = form_data['category']
                if product.description != form_data['description']:
                    product.description = form_data['description']
                if product.umo != form_data['umo']:
                    product.umo = form_data['umo']
                if product.specification != form_data['specification']:
                    product.specification = form_data['specification']
                if product.stock != form_data['stock']:
                    product.stock = form_data['stock']
                if product.minimum_stock_level != form_data['minimum_stock_level']:
                    product.minimum_stock_level = form_data['minimum_stock_level']
                if product.rack_no != form_data['rack_no']:
                    product.rack_no = form_data['rack_no']
                if product.tray_no != form_data['tray_no']:
                    product.tray_no = form_data['tray_no']
                product.updated_by = self.request.user.id
                product.save()
                if form_data['image']:
                    if product.image:
                        old_image = '/'.join(product.image.split('/')[4:])
                        if default_storage.exists(old_image):
                            default_storage.delete(old_image)
                    product.save_image_url(form_data["image"], get_secured_url(
                            self.request) + self.request.META["HTTP_HOST"])
                return redirect('products:products-list')
            
        except Exception as e:
            messages.error(self.request, str(e))
            return redirect(self.request.META['HTTP_REFERER'])


class ProductProperty(View):
    template_name = "products/attribute.html"

    def get(self, request, id):
        product = Product.objects.single_product(id)
        properties = ProductAttribute.objects.filter(product=product)
        attribute = Attribute.objects.all()
        previous_url = request.META.get('HTTP_REFERER')
        context = {
            "product": product,
            "properties": properties,
            "previous_url": previous_url,
            "attribute": attribute
        }

        return render(request, self.template_name, context)

    def post(self, request, id):
        product = Product.objects.single_product(id)
        try:
            data = json.loads(request.POST.get("data"))
            if data["attribute"] != '' and data["value"] != '':
                attribute = data["attribute"]
                value = data["value"].strip()
                obj, created = Attribute.objects.get_or_create(

products/templates/bom/bom_list.html
{% extends "base.html" %}
{% load static %}
{% load product_extras %}

{% block title %}List of BOM{% endblock %}

{% block css %}

{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
  href="{% url 'products:products-list' %}">Products</a> / <b class="text-dark">Bill Of Matrials<b></li>
{% endblock %}

{% block head %}
List of BOM
{% endblock %}

{% block content %}

<div class="container mt-3 mb-5">
  <div class="row">
    <div class="col-4">
      <input type="text" class="form-control" id="id_search" name="search" placeholder="Search" />      
    </div>

    <div class="col-4">
      
    </div>
    <div class="col-4">
      <a href="{% url 'products:products-create' %}"><button type="button" class="btn btn-success  mb-2"
        style="float: right; ">Add New Bill Of Materials </button></a>
    </div>
    <div class="col-12">

      <!-- Basic Bootstrap Table -->
      <div class="card">
        
        
        {% comment %} <a class="btn btn-success col-1">Add New</a> {% endcomment %}
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>No</th>
                {% comment %} <th>Code</th> {% endcomment %}
                <th>Image</th>
                <th>Code</th>
                <th>Name</th>                
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0" id="id_products_list">
              {% for product in products %}
              <tr >
                <td> 
                  {{ forloop.counter|adjust_for_pagination:data }}
                </td>
                <td><img src="{{product.image}}" height="50px" width="50px"></td>
                <td>{{product.code}}</td>
                <td>{{product.name}}</td>
                <td> 
                    {% if product.is_active %}
                    <i class="fas fa-check text-success" style="font-size: 15px;"></i>
                    {% else %}
                    <i class="fas fa-times text-danger" style="font-size: 15px;"></i>
                    {% endif %}
                </td>
                <td>
                  <a href="{% url 'products:product-bom' product.code %}"
                                class="btn btn-success btn-circle " title="Bill Of Matrials"><i class="fa-solid fa-magnet"></i></i></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          
        </div>
        
      </div>
      <!--/ Basic Bootstrap Table -->
    </div>
  </div>
  <div class="row container-fluid mt-2">
    {% if products.paginator.num_pages > 1 %}
    {% include 'components/pagination.html' with items=products paginator=products.paginator %}
    {% endif %}
</div>
</div>
<div class="mt-5"></div>

{% endblock content %}

{% block js %}
<script>
  $('#bom').addClass('active open');
  $('#product-bom').addClass('active')
</script>

<script>
  $(document).on("keyup", "#id_search", function () {
    var query = this.value;
    // var category = $()
    $.ajax({
        url: '/products/search-bom/',
        type: 'GET',
        data: { 'query': query},
        success: function (data) {
            $('#id_products_list').html(data.data);
        }
    });
});
</script>
{% endblock js %}

products/templates/bom/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add New B.O.M{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://basuriautomotive.com/assets/css/aiz-core.css">
{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
        href="{% url 'products:bom-list' %}">BOM</a> / <b class="text-dark">Add<b></li>
{% endblock %}

{% block head %}
New BOM
{% endblock %}

{% block content %}
<div class="container-fluid ">
    <div class="row">
        {% comment %} <div class="col-6 card mb-4">
          <div class="card-header">
            <h5>Create BOM</h5>
          </div>
          <div class="card-body">
                <form class="mt-3 " method="post" enctype="multipart/form-data" action='.'
                    data-url='{{ request.build_absolute_uri|safe }}' id="create-product">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    <label for="productCode">Main Part No.:</label>
                                    <input type="text" class="form-control" name="productCode[]" >
                                </div>
                            </div>
                            <div class="row">
                                <div id="billingFields" class="mt-4">
                                    <div class="row billing-entry">
                                        <div class="form-group col-md-3">
                                            <label for="productCode">Child Part No.:</label>
                                            <input type="text" class="form-control" name="productCode[]" >
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="quantity">Quantity:</label>
                                            <input type="text" class="form-control" name="quantity[]" >
                                        </div>
                                        <div class="form-group col-md-2">
                                            <button type="button" class="btn btn-danger remove-billing mt-4"><i class="fa-solid fa-trash"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <button type="button" class="btn btn-primary mt-3" id="add-row"><i class="fa-solid fa-plus"></i></button>
                                    <button type="submit" class="btn btn-success mt-3" id="add-row">Add</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div> {% endcomment %}

        <div class="col-4 card m-3">
            <div class="card-header">
              <h5>Upload BOM File</h5>
            </div>
            <div class="card-body">
                  <form class="mt-3 " method="post" enctype="multipart/form-data" action='.'
                      data-url='{{ request.build_absolute_uri|safe }}' id="create-product">
                      {% csrf_token %}
                      {{form}}
                      <button class="btn btn-success mt-2" type="submit">Upload CSV</button>
                  </form>
              </div>
            </div>
          </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script>
    $('#bom').addClass('active open');
  $('#add-bom').addClass('active')
</script>
<script src="{% static 'js/jquery.form.js'%}"></script>
<script>
    // Add Billing Field
    //document.getElementById("").addEventListener("click", function() {
    $("#add-row").click(function(){
        
        const billingFieldsDiv = document.getElementById("billingFields");
        const billingCount = billingFieldsDiv.querySelectorAll(".billing-entry").length + 1;

        const billingEntry = document.createElement("div");
        billingEntry.className = "form-row billing-entry";

        billingEntry.innerHTML = `
        <div class="row">
            <div class="form-group col-md-3">
                <label for="productCode${billingCount}">Child Part No.:</label>
                <input type="text" class="form-control" name="productCode[]" required>
            </div>
            <div class="form-group col-md-3">
                <label for="quantity${billingCount}">Quantity:</label>
                <input type="text" class="form-control" name="quantity[]" >
            </div>
            <div class="form-group col-md-2">
                <button type="button" class="btn btn-danger remove-billing mt-4"><i class="fa-solid fa-trash"></i></button>
            </div>
        </div>
        `;

        billingFieldsDiv.appendChild(billingEntry);

        // Add an event listener to the new remove button
        const newRemoveButton = billingEntry.querySelector(".remove-billing");
        newRemoveButton.addEventListener("click", function() {
            billingEntry.remove();
        });
    });

    // Remove Billing Field
    document.getElementById("billingFields").addEventListener("click", function(e) {
        if (e.target && e.target.className == "btn btn-danger remove-billing") {
            e.target.parentElement.parentElement.remove();
        }
    });
</script>
{% endblock %}

products/templates/bom/singel_bom.html
{% extends "base.html" %}
{% load static %}
{% load product_extras %}

{% block title %}BOM OF {{code}}-{{name}}{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
{% endblock css %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page"><a
  href="{% url 'products:products-list' %}">Products</a> / <b class="text-dark">BOM OF {{name}}</b></li>
{% endblock %}

{% block head %}
BOM OF {{name}}
{% endblock %}

{% block content %}

<div class="container mt-3 mb-5">
  <div class="row">
        <div class="col-12">
          {% comment %} <a href="{% url 'products:products-create' %}"><button type="button" class="btn btn-success  mb-2"
            style="float: right; ">Add New Product</button></a> {% endcomment %}
        </div>
        <div class="col-12">
          <!-- Basic Bootstrap Table -->
          <div class="card">
            
            <div class="card-header">
              <h5 class="">BOM OF {{code}}-{{name}} </h5>
              {% if user.role == 'SUPER_ADMIN' %}
              <a href="{% url 'products:bom-delete' code %}"
                   class="btn btn-danger btn-circle " title="Delete"><i class="fa-solid fa-trash"></i></a>
              <a href="{% url 'products:bom-create' %}"
                   class="btn btn-success btn-circle " title="Delete"><i class="fa-solid fa-plus"></i></a>
              {% endif %}
            </div>
            
            <table id="example" class="display nowrap table mt-3 mb-3" style="width:100%">
              <thead>
                <tr>
                  <th>Code:<b>{{code}}</b></th>
                  <th>Name:<b>{{name}}</b></th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
                  
              </thead>
              <tbody>
                <tr>
                  <th>Part No.</th>
                  <th>Name</th>
                  <th>QTY</th>
                  <th>Current<br>Stock</th>
                  <th>Vendor</th>
                  <th>price</th>
                  <th>Total Price</th>
                  <th>Action</th>
                  
              </tr>
                {%for i in components %}
                  <tr>
                      <td>{{i.part_no}}</td>
                      <td>{{i.name}}</td>
                      <td>{{i.qty}}</td>
                      <td>{{i.stock}}</td>
                      <td>{{i.part_no|get_vendor}}</td>
                      <td>{{i.part_no|get_price }}</td>
                      <td>{{i.part_no|get_total_price:i.qty}}</td>
                      <td>
                        {% if user.role == 'SUPER_ADMIN' %}
                        {% if i.part_no %}
                        <a href="{% url 'products:child-part-delete' i.id %}"
                                  class="btn btn-danger btn-circle " title="Delete"><i class="fa-solid fa-trash"></i></a>
                        {% endif %}
                        {% endif %}
                      </td>
                      
                  </tr>
                  {% endfor %}
              </tbody>
              <tfoot>
                  <tr>
                    <th>Code:<b>{{code}}</b></th>
                    <th>Name:<b>{{name}}</b></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
              </tfoot>
          </table>
          </div>
          
        </div>
  </div>
  
</div>
<div class="mt-5"></div>

{% endblock content %}

{% block js %}
<script type="text/javascript" src = "https://code.jquery.com/jquery-3.7.0.js"></script>
    <script type="text/javascript" src = "https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src = "https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src = "https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src = "https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
<script>
  $('#bom').addClass('active open');
  $('#product-bom').addClass('active')
</script>
<script>
  $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        "bPaginate": false,
        searching: false, paging: false, info: false,"ordering": false,
        buttons: [
            'excel', 'pdf', 'print'
        ]
    } );
} );
</script>
{% endblock js %}