base/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (UserRegister,
                    Logout,
                    VerifyOtp,
                    Dashboard,
                    ResetPasswordView,
                    ForgotPasswordView,
                    ResendOtp, ChangePassword
                    )

from base.api import UserLoginView

app_name = "base"

urlpatterns = [
    # path("register/", UserRegister.as_view(), name="register"),
    path("dashboard/", login_required(Dashboard.as_view()), name="dashboard"),
    path("logout/", login_required(Logout.as_view()), name="logout"),
    path("otp-verification/", VerifyOtp.as_view(), name="otp_verify"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgotpassword"),
    path("reset-password/", ResetPasswordView.as_view(), name="resetpassword"),
    path("resend/", ResendOtp.as_view(), name="resend-otp"),
    path('password/change/', login_required(ChangePassword.as_view()),
         name='change-password'),
    path('simple-login/', UserLoginView.as_view(), name="simple-login"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.generic.base import TemplateView

from base.views import Login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', never_cache(Login.as_view()), name="login"),
    path('', include('base.urls', namespace='base')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/',include('products.urls', namespace='products')),
    path('utils/', include('utils.urls', namespace='utils')),
    path('inventry/', include('inventry.urls', namespace='inventry')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('purchase/', include('purchase.urls', namespace='purchase')),
    path('dhl/', include('dhl_api.urls', namespace='dhl_api')),
    path('inward/', include('inward.urls', namespace='inward')),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),  #add the robots.txt file
    
]

# Static files Setup
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True, blank=True)
    updated_by = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

base/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.validators import validate_email
from django.core.validators import RegexValidator

from users.models import User
from utils.views import is_email

class UserRegisterForm(forms.Form):
    mobile_regex = RegexValidator(
        regex=r'^[6-9][0-9]{9}', message="Mobile number must be entered with code in the format: 9999999999. It must start with 6, 7, 8, 9")
    first_name = forms.CharField(max_length=75, strip=True, required=True, label='First Name',
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name *','autofocus':'',}))
    last_name = forms.CharField(max_length=75, strip=True, required=False, label='Last Name',
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    email = forms.CharField(required=False, label='Email ', strip=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}))
    mobile = forms.CharField(
        required=True, max_length=14, label="Mobile No.", widget=forms.NumberInput(attrs={"class": "form-control", "type": "tel"}), validators=[mobile_regex])
    country_code = forms.CharField(required=True,
                                   widget=forms.HiddenInput())
    password1 = forms.CharField(required=True, label=("Password"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password *'}))
    password2 = forms.CharField(required=True, label=("Password Confirmation"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password *'}))
    terms_and_condition = forms.BooleanField(
        required=True, label="Terms and Condition", widget=forms.CheckboxInput(attrs={'style': 'width:15px;height:15px;'}))
    
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields["terms_and_condition"].initial = True

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    "The password fields didn't match.")
        return password2

    def clean_mobile(self):
        mobile = self.cleaned_data.get('mobile')
        country_code = self.cleaned_data.get('country_code')
        if User.objects.filter(mobile__iexact=mobile).exists():
            if User.objects.get(mobile=mobile).role == Roles.USER.value:
                return mobile
            raise forms.ValidationError(
                "Business with this mobile number already exist !")
        return mobile

    def clean_password(self):
        password = self.cleaned_data.get('password1')
        password_validation.validate_password(password)
        return password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email != "" and email != None:
            if is_email(email):
                if User.objects.filter(email__iexact=email).exists():
                    raise forms.ValidationError(
                        "User with this email already exist !")
            else:
                raise forms.ValidationError("Your Email wasn't valid !")
        return email

    def clean_password(self):
        password = self.cleaned_data.get('password1')
        password_validation.validate_password(password)
        return password


class ResetPasswordForm(forms.Form):

    password1 = forms.CharField(required=True, label=("Password"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label=("Password Confirmation"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    "The password fields didn't match.")
        return password2

    def clean_password(self):
        password = self.cleaned_data.get('password1')
        password_validation.validate_password(password)
        return password
    

class ChangePasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'password_incorrect': "Your old password was entered incorrectly. Please enter it again.",
    }

    old_password = forms.CharField(
        label="Old Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autofocus': True, 'class': 'form-control'}),
    )

    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label="Confirm Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

    

base/templates/base/login.html
{% load static %}
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="{% static 'assets/' %}/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Login Basic - Pages | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logoB.ico' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'assets/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'assets/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="{% static 'assets/vendor/css/pages/page-auth.css' %}" />
    <!-- Helpers -->
    <script src="{% static 'assets/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'assets/js/config.js' %}"></script>
  </head>

  <body>
    <!-- Content -->

    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
          
          <!-- Register -->
          <div class="card">
            <div class="card-body">
              {% include 'components/messages.html' %}
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <a href="index.html" class="app-brand-link gap-2">
                  <h1>KrunalIndustries</h1>
                </a>
              </div>
              <!-- /Logo -->
              <h4 class="mb-2">Welcome to KrunalIndustries! 👋</h4>
              <p class="mb-4">Please sign-in to your account and start the adventure</p>

              <form id="formAuthentication" class="mb-3" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="email" class="form-label">Email or Username</label>
                  <input
                    type="text"
                    class="form-control"
                    id="email"
                    name="username"
                    placeholder="Enter your email or username"
                    autofocus
                    required
                  />
                </div>
                <div class="mb-3 form-password-toggle">
                  <div class="d-flex justify-content-between">
                    <label class="form-label" for="password">Password</label>
                    <a href="{% url 'base:forgotpassword' %}">
                      <small>Forgot Password?</small>
                    </a>
                  </div>
                  <div class="input-group input-group-merge">
                    <input
                      type="password"
                      id="password"
                      class="form-control"
                      name="password"
                      placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                      aria-describedby="password"
                      required
                    />
                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                  </div>
                </div>
                <div class="mb-3">
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="remember-me" />
                    <label class="form-check-label" for="remember-me"> Remember Me </label>
                  </div>
                </div>
                <div class="mb-3">
                  <button class="btn btn-primary d-grid w-100" type="submit">Sign in</button>
                </div>
              </form>

              <p class="text-center">
                <span>New on our platform?</span>
                <a href="{% url 'login' %}">
                  <span>Create an account</span>
                </a>
              </p>
            </div>
          </div>
          <!-- /Register -->
        </div>
      </div>
    </div>

    <!-- / Content -->

{% include 'base/js.html' %}
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script>
      $(".preloader ").fadeOut();
    </script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

base/templates/base/password-change.html
{% extends "base.html" %}
{% load static %}

{% block title %}Change Password{% endblock %}
{% block head %}
Change Password
{% endblock %}

{% block next_page %}
<li class="breadcrumb-item text-muted active" aria-current="page">Change Password</li>
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <h4 class="card-title ml-5 mt-2 text-center ">Change Password</h4>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{ form.old_password.label }}</label>
                                {{ form.old_password }}
                                <span class="text-danger">{{ form.old_password.errors }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{ form.new_password1.label }}</label>
                                {{ form.new_password1 }}
                                <span class="text-danger">{{ form.new_password1.errors }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{ form.new_password2.label }}</label>
                                {{ form.new_password2 }}
                                <span class="text-danger">{{ form.new_password2.errors }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-3">
                            <div class="form-group">
                                <button class="btn btn-primary bg-gradient-primary" type="submit">Change Password
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $('#settings').addClass('active open');
    $('#change-pass').addClass('active')
</script>
{% endblock %}

base/templates/base/register.html
{% load static %}
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="{% static 'assets/' %}/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Login Basic - Pages | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logoB.ico' %}" />

    {% include 'base/css.html' %}

    <!-- Helpers -->
    <script src="{% static 'assets/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'assets/js/config.js' %}"></script>
    <link rel="stylesheet" href="{% static 'assets/extra-libs/countrycode/css/intlTelInput.css' %}">
    <link rel="stylesheet" href="{% static 'assets/extra-libs/countrycode/css/demo.css'%}">
  </head>

  <body>
    <!-- Content -->

    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
        <!-- Register Card -->
        <div class="card">
              <div class="card-body">
                <!-- Logo -->
                <div class="app-brand justify-content-center">
                  <a href="index.html" class="app-brand-link gap-2">
                    <img src="{% static 'assets/img/logo.jpeg' %}" width="120px" height = "80px">                    
                  </a>
                </div>
                <!-- /Logo -->
                <h4 class="mb-2">Adventure starts here 🚀</h4>
                <p class="mb-4">Make your app management easy and fun!</p>
            
                <form id="formAuthentication" class="mb-3" method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="firstname" class="form-label">First Name</label>
                    {{form.first_name}}
                    {% comment %} <input
                      type="text"
                      class="form-control"
                      id="username"
                      name="username"
                      placeholder="Enter your username"
                      autofocus
                    /> {% endcomment %}
                  </div>
                  <div class="mb-3">
                    <label for="lastname" class="form-label">Last Name</label>
                    {{form.last_name}}
                    {% comment %} <input
                      type="text"
                      class="form-control"
                      id="username"
                      name="username"
                      placeholder="Enter your username"
                      autofocus
                    /> {% endcomment %}
                  </div>
                  <div class="mb-3">
                    <label for="mobile" class="form-label">Mobile</label>
                    {% comment %} <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email" /> {% endcomment %}
                    {{form.country_code}}
                    {{form.mobile}}
                  </div>
                  <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    {% comment %} <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email" /> {% endcomment %}
                    {{form.email}}
                  </div>
                  <div class="mb-3 form-password-toggle">
                    <label class="form-label" for="password">Password</label>
                    <div class="input-group input-group-merge">
                      {% comment %} <input
                        type="password"
                        id="password"
                        class="form-control"
                        name="password"
                        placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                        aria-describedby="password"
                      /> {% endcomment %}
                      {{form.password1}}
                      <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                    </div>
                  </div>

                  <div class="mb-3 form-password-toggle">
                    <label class="form-label" for="password">Confirm Password</label>
                    <div class="input-group input-group-merge">
                      {% comment %} <input
                        type="password"
                        id="password"
                        class="form-control"
                        name="password"
                        placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                        aria-describedby="password"
                      /> {% endcomment %}
                      {{form.password2}}
                      <span class="input-group-text cursor-pointer"></span>
                    </div>
                  </div>
              
                  <div class="mb-3">
                    <div class="form-check">
                      {% comment %} <input class="form-check-input" type="checkbox" id="terms-conditions" name="terms" /> {% endcomment %}
                      {{form.terms_and_condition}}
                      <label class="form-check-label" for="terms-conditions">
                        I agree to
                        <a href="javascript:void(0);">privacy policy & terms</a>
                      </label>
                    </div>
                  </div>
                  <button class="btn btn-primary d-grid w-100">Sign up</button>
                </form>
            
                <p class="text-center">
                  <span>Already have an account?</span>
                  <a href="{% url 'login' %}">
                    <span>Sign in instead</span>
                  </a>
                </p>
              </div>
            </div>
            <!-- Register Card -->
        </div>
      </div>
    </div>

    <!-- / Content -->

    {% include 'base/js.html' %}
    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="{% static 'assets/extra-libs/countrycode/js/intlTelInput.js' %}"></script>
    
    <script>
      function checkempty() {
        var $nonempty = $('#error-msg').filter(function () {
          return $(this).text() == ''
        });
        if ($nonempty.length > 0) { // if empty spans available
          $('#register_btn').prop("disabled", false); // disable button
        } else {
          $('#register_btn').prop("disabled", true); // otherwise enable it
        }
      }
    </script>
  <script>
    // get the country data from the plugin
    var countryData = window.intlTelInputGlobals.getCountryData(),
      input = document.querySelector("#id_mobile"),
      addressDropdown = document.querySelector("#id_country_code"),
      errorMsg = document.querySelector("#error-msg"),
      validMsg = document.querySelector("#valid-msg");

    var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

    var iti = window.intlTelInput(input, {
      utilsScript: "{% static 'assets/extra-libs/countrycode/js/utils.js' %}",
    });

    var reset = function () {
      input.classList.remove("error");
      errorMsg.innerHTML = "";
      errorMsg.classList.add("hide");
      validMsg.classList.add("hide");
    };

    input.addEventListener('blur', function () {
      reset();
      if (input.value.trim()) {
        if (iti.isValidNumber()) {
          validMsg.classList.remove("hide");
        } else {
          input.classList.add("error");
          var errorCode = iti.getValidationError();
          errorMsg.innerHTML = errorMap[errorCode];
          errorMsg.classList.remove("hide");
        }
      }
      checkempty();
    });

    // populate the country dropdown
    for (var i = 0; i < countryData.length; i++) {
      var country = countryData[i];
      var optionNode = document.createElement("option");
      optionNode.value = country.dialCode;
      var textNode = document.createTextNode(country.dialCode);
      optionNode.appendChild(textNode);
      addressDropdown.appendChild(optionNode);
    }
    // set it's initial value
    addressDropdown.value = iti.getSelectedCountryData().dialCode;

    // listen to the telephone input for changes
    input.addEventListener('countrychange', function (e) {
      addressDropdown.value = iti.getSelectedCountryData().dialCode;
    });

    // listen to the address dropdown for changes
    addressDropdown.addEventListener('change', function () {
      iti.setCountry(this.value);
    });
    $("#id_mobile").attr("placeholder", "Phone No..")
    input.addEventListener('change', reset);
    input.addEventListener('keyup', reset);

  </script>
  <script>
    $(".preloader ").fadeOut();
  </script>
  <script>
    $(document).ready(function () {
      $('#register').on('submit', function () {
        var form = $(this);
        $.ajax({
          url: form.attr('data-url'),
          data: form.serialize(),
          type: form.attr('method'),
          dataType: 'json',
          success: function (data) {
            location.replace('{% url "base:otp_verify" %}')
          },
          error: function (data) {
            $("#password2").text(data.responseJSON.password2)
            $("#first_name").text(data.responseJSON.first_name)
            $("#last_name").text(data.responseJSON.last_name)
            $("#mobile").text(data.responseJSON.mobile)
            $("#email").text(data.responseJSON.email)
            $("#password1").text(data.responseJSON.password1)

          }
        })
        return false;
      })
    })
  </script>
  </body>
</html>